import json
from pathlib import Path


OUT = Path(__file__).resolve().parent / "tokenstream-stride-dfd-trust-boundaries.json"


def boundary(cell_id, name, x, y, w, h, description, contained, crossing):
    return {
        "id": cell_id,
        "shape": "trust-boundary-box",
        "position": {"x": x, "y": y},
        "size": {"width": w, "height": h},
        "attrs": {"label": {"text": name}},
        "zIndex": 1,
        "data": {
            "type": "tm.BoundaryBox",
            "name": name,
            "description": description,
            "isTrustBoundary": True,
            "hasOpenThreats": False,
            "crossingFlows": crossing,
            "containedElements": contained,
        },
    }


def actor(cell_id, name, x, y, description):
    return {
        "id": cell_id,
        "shape": "actor",
        "position": {"x": x, "y": y},
        "size": {"width": 150, "height": 72},
        "attrs": {"text": {"text": name}, "label": {"text": name}},
        "zIndex": 3,
        "data": {
            "type": "tm.Actor",
            "name": name,
            "description": description,
            "isTrustBoundary": False,
            "outOfScope": False,
            "reasonOutOfScope": "",
            "hasOpenThreats": False,
            "providesAuthentication": False,
            "threats": [],
        },
    }


def process(cell_id, name, x, y, description, privilege="service", web=True):
    return {
        "id": cell_id,
        "shape": "process",
        "position": {"x": x, "y": y},
        "size": {"width": 150, "height": 76},
        "attrs": {
            "text": {"text": name},
            "body": {"stroke": "#333333", "strokeWidth": 1.5, "strokeDasharray": None},
        },
        "zIndex": 3,
        "data": {
            "type": "tm.Process",
            "name": name,
            "description": description,
            "isTrustBoundary": False,
            "outOfScope": False,
            "reasonOutOfScope": "",
            "hasOpenThreats": False,
            "handlesCardPayment": False,
            "handlesGoodsOrServices": False,
            "isWebApplication": web,
            "privilegeLevel": privilege,
            "threats": [],
        },
    }


def store(cell_id, name, x, y, description, stores_credentials=False):
    return {
        "id": cell_id,
        "shape": "store",
        "position": {"x": x, "y": y},
        "size": {"width": 160, "height": 72},
        "attrs": {"text": {"text": name}},
        "zIndex": 3,
        "data": {
            "type": "tm.Store",
            "name": name,
            "description": description,
            "isTrustBoundary": False,
            "outOfScope": False,
            "reasonOutOfScope": "",
            "hasOpenThreats": False,
            "isALog": False,
            "isEncrypted": False,
            "isSigned": False,
            "storesCredentials": stores_credentials,
            "storesInventory": True,
            "threats": [],
        },
    }


def flow(cell_id, name, source, target, description, protocol, public, encrypted, bidirectional, boundaries, vertices=None):
    return {
        "id": cell_id,
        "shape": "flow",
        "source": {"cell": source},
        "target": {"cell": target},
        "vertices": vertices or [],
        "labels": [{"attrs": {"labelText": {"text": name}}}],
        "zIndex": 4,
        "data": {
            "type": "tm.Flow",
            "name": name,
            "description": description,
            "isTrustBoundary": False,
            "outOfScope": False,
            "reasonOutOfScope": "",
            "hasOpenThreats": False,
            "isBidirectional": bidirectional,
            "isEncrypted": encrypted,
            "isPublicNetwork": public,
            "protocol": protocol,
            "threats": [],
            "trustBoundaryIds": boundaries,
        },
    }


cells = [
    boundary(
        "tb-user-controlled",
        "External / user-controlled",
        20,
        30,
        255,
        650,
        "Client applications, human administrators, corpus/source owners, and source systems outside the TokenStream runtime.",
        ["actor-client-app", "actor-human-admin", "actor-corpus-source", "actor-local-chat-ui"],
        ["flow-chat-request", "flow-local-chat-request", "flow-admin-session", "flow-source-upload-fetch"],
    ),
    boundary(
        "tb-tokenstream-runtime",
        "TokenStream self-hosted runtime",
        330,
        30,
        760,
        640,
        "Self-hosted TokenStream services and stores controlled by the deployer/operator.",
        [
            "process-dev-ui",
            "process-config-auth",
            "process-orchestrator-api",
            "process-retrieval-api",
            "process-ingestion-worker",
            "process-tei-embedder",
            "store-config-db",
            "store-runtime-snapshots",
            "store-object-storage",
            "store-qdrant-vectors",
            "store-sqlite-lexical-graph",
        ],
        [
            "flow-chat-request",
            "flow-local-chat-request",
            "flow-admin-session",
            "flow-source-upload-fetch",
            "flow-provider-request",
            "flow-mcp-tool-call",
        ],
    ),
    boundary(
        "tb-admin-control-plane",
        "Administrative control plane",
        355,
        300,
        360,
        340,
        "Administration, authentication, authorization, configuration, and runtime snapshot generation.",
        ["process-dev-ui", "process-config-auth", "store-config-db", "store-runtime-snapshots"],
        ["flow-admin-session", "flow-management-config-write", "flow-runtime-snapshot-reload"],
    ),
    boundary(
        "tb-rag-index-plane",
        "RAG / indexing data plane",
        735,
        210,
        325,
        430,
        "Retrieval, ingestion, embeddings, object storage, and retrieval indexes.",
        [
            "process-retrieval-api",
            "process-ingestion-worker",
            "process-tei-embedder",
            "store-object-storage",
            "store-qdrant-vectors",
            "store-sqlite-lexical-graph",
        ],
        ["flow-source-upload-fetch", "flow-index-write-query"],
    ),
    boundary(
        "tb-external-providers-tools",
        "External providers / tools",
        1145,
        30,
        285,
        430,
        "LLM providers and MCP/tool servers outside the TokenStream runtime trust boundary.",
        ["actor-llm-provider", "actor-mcp-server"],
        ["flow-provider-request", "flow-mcp-tool-call"],
    ),
    actor(
        "actor-client-app",
        "Client application",
        70,
        100,
        "Application backend calling TokenStream machine APIs. End users are expected to interact with the client application, not directly with TokenStream.",
    ),
    actor(
        "actor-human-admin",
        "Human admin",
        70,
        265,
        "Trusted operator using dev-ui for administrative and configuration activities.",
    ),
    actor(
        "actor-corpus-source",
        "Corpus source",
        70,
        410,
        "Corpus/source owner inputs and source systems, including uploaded files, URLs, repositories, archives, or other externally controlled material.",
    ),
    actor(
        "actor-local-chat-ui",
        "Optional local chat UI",
        70,
        545,
        "Optional adjacent local chat UI, such as Open WebUI, using TokenStream as a backend API rather than as an administrative surface.",
    ),
    process(
        "process-orchestrator-api",
        "orchestrator-api",
        520,
        95,
        "OpenAI-compatible policy-aware router for LLM requests, retrieval calls, and MCP tool calls.",
        privilege="service",
        web=True,
    ),
    process(
        "process-dev-ui",
        "dev-ui",
        385,
        360,
        "Browser administrative surface. Intended for trusted administrators only.",
        privilege="admin",
        web=True,
    ),
    process(
        "process-config-auth",
        "config_auth",
        545,
        360,
        "Authentication, authorization, users, RBAC, API keys, provider registry, policies, corpora, sources, jobs, and runtime snapshot export.",
        privilege="admin",
        web=True,
    ),
    process(
        "process-retrieval-api",
        "retrieval-api",
        795,
        105,
        "Corpus-scoped retrieval API used by orchestrator-api for RAG and retrieval tools.",
        privilege="service",
        web=True,
    ),
    process(
        "process-ingestion-worker",
        "ingestion-worker",
        795,
        315,
        "Fetches/uploads source content, parses and chunks material, requests embeddings, and writes retrieval indexes.",
        privilege="service",
        web=False,
    ),
    process(
        "process-tei-embedder",
        "TEI embedder",
        795,
        505,
        "Embedding service used by the ingestion worker to convert chunks into vectors.",
        privilege="service",
        web=True,
    ),
    store(
        "store-config-db",
        "config_auth SQLite",
        385,
        505,
        "Users, sessions, RBAC roles, API key hashes, providers, policies, corpora, sources, jobs, and audit-relevant administrative state.",
        stores_credentials=True,
    ),
    store(
        "store-runtime-snapshots",
        "runtime snapshots",
        545,
        505,
        "Generated runtime configuration snapshots, including providers, policies, API key material/references, RAG settings, processors, and MCP settings.",
        stores_credentials=True,
    ),
    store(
        "store-object-storage",
        "object storage",
        955,
        315,
        "Uploaded and fetched source objects, typically S3-compatible or MinIO-backed.",
        stores_credentials=False,
    ),
    store(
        "store-qdrant-vectors",
        "Qdrant vectors",
        955,
        445,
        "Dense vector retrieval indexes and related metadata.",
        stores_credentials=False,
    ),
    store(
        "store-sqlite-lexical-graph",
        "SQLite lexical/graph",
        955,
        565,
        "Lexical, metadata, reference, alias, and graph-aware retrieval artifacts.",
        stores_credentials=False,
    ),
    actor(
        "actor-llm-provider",
        "LLM provider",
        1215,
        115,
        "External or local LLM provider endpoint receiving provider requests from orchestrator-api.",
    ),
    actor(
        "actor-mcp-server",
        "MCP server / tool",
        1215,
        295,
        "External or adjacent MCP server/tool endpoint invoked by orchestrator-api under configured policy.",
    ),
    flow(
        "flow-chat-request",
        "chat request",
        "actor-client-app",
        "process-orchestrator-api",
        "Client chat/model/RAG request and response. May include prompts, selected model/pipeline, retrieval intent, metadata, and machine API key authentication.",
        "HTTP(S) / OpenAI-compatible API",
        public=True,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-user-controlled", "tb-tokenstream-runtime"],
        vertices=[{"x": 295, "y": 136}, {"x": 500, "y": 136}],
    ),
    flow(
        "flow-local-chat-request",
        "chat request",
        "actor-local-chat-ui",
        "process-orchestrator-api",
        "Optional local chat UI request/response using TokenStream machine APIs. This is not an administrative control-plane flow.",
        "HTTP(S) / OpenAI-compatible API",
        public=True,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-user-controlled", "tb-tokenstream-runtime"],
        vertices=[{"x": 300, "y": 581}, {"x": 500, "y": 156}],
    ),
    flow(
        "flow-admin-session",
        "admin session",
        "actor-human-admin",
        "process-dev-ui",
        "Trusted administrator browser session to dev-ui. This flow exists to show the external-to-admin-plane trust boundary before the management config write flow.",
        "HTTP(S)",
        public=True,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-user-controlled", "tb-tokenstream-runtime", "tb-admin-control-plane"],
        vertices=[{"x": 300, "y": 300}, {"x": 360, "y": 390}],
    ),
    flow(
        "flow-management-config-write",
        "management config write",
        "process-dev-ui",
        "process-config-auth",
        "Management writes for users, RBAC, API keys, providers, policies, corpora, sources, jobs, processors, retrieval profiles, RAG settings, and MCP settings.",
        "same-origin HTTP routes / in-process calls",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-admin-control-plane"],
    ),
    flow(
        "flow-config-state-write",
        "management config write",
        "process-config-auth",
        "store-config-db",
        "Persistence of management configuration and authentication/authorization state into config_auth SQLite.",
        "SQLite",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-admin-control-plane"],
    ),
    flow(
        "flow-runtime-snapshot-export",
        "management config write",
        "process-config-auth",
        "store-runtime-snapshots",
        "Export of management configuration into runtime snapshot artifacts consumed by runtime services.",
        "filesystem",
        public=False,
        encrypted=False,
        bidirectional=False,
        boundaries=["tb-admin-control-plane"],
    ),
    flow(
        "flow-runtime-snapshot-reload",
        "runtime snapshot reload",
        "store-runtime-snapshots",
        "process-orchestrator-api",
        "orchestrator-api loads/reloads runtime snapshots containing provider, policy, key, RAG, retrieval, and MCP configuration.",
        "filesystem / local volume",
        public=False,
        encrypted=False,
        bidirectional=False,
        boundaries=["tb-tokenstream-runtime", "tb-admin-control-plane"],
        vertices=[{"x": 620, "y": 240}, {"x": 590, "y": 190}],
    ),
    flow(
        "flow-orchestrator-retrieval-query",
        "index write/query",
        "process-orchestrator-api",
        "process-retrieval-api",
        "RAG retrieval request/response from orchestrator-api to retrieval-api before index lookups.",
        "HTTP",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-tokenstream-runtime", "tb-rag-index-plane"],
    ),
    flow(
        "flow-retrieval-qdrant-query",
        "index write/query",
        "process-retrieval-api",
        "store-qdrant-vectors",
        "Retrieval-api query against Qdrant dense vector indexes.",
        "HTTP",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-retrieval-sqlite-query",
        "index write/query",
        "process-retrieval-api",
        "store-sqlite-lexical-graph",
        "Retrieval-api query against lexical, metadata, reference, alias, and graph indexes.",
        "SQLite",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-source-upload-fetch",
        "source upload/fetch",
        "actor-corpus-source",
        "process-ingestion-worker",
        "Source upload or URL/repository/archive fetch into ingestion. Source material is user-controlled or externally controlled before ingestion.",
        "HTTP(S) / S3 / filesystem",
        public=True,
        encrypted=False,
        bidirectional=False,
        boundaries=["tb-user-controlled", "tb-tokenstream-runtime", "tb-rag-index-plane"],
        vertices=[{"x": 300, "y": 476}, {"x": 770, "y": 350}],
    ),
    flow(
        "flow-ingestion-object-write",
        "source upload/fetch",
        "process-ingestion-worker",
        "store-object-storage",
        "Storage and later readback of uploaded or fetched source objects.",
        "S3-compatible / local object storage",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-ingestion-embedding",
        "index write/query",
        "process-ingestion-worker",
        "process-tei-embedder",
        "Chunk embedding request/response used before vector index writes.",
        "HTTP",
        public=False,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-ingestion-qdrant-write",
        "index write/query",
        "process-ingestion-worker",
        "store-qdrant-vectors",
        "Ingestion writes/upserts dense vectors and metadata to Qdrant.",
        "HTTP",
        public=False,
        encrypted=False,
        bidirectional=False,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-ingestion-sqlite-write",
        "index write/query",
        "process-ingestion-worker",
        "store-sqlite-lexical-graph",
        "Ingestion writes chunks, metadata, lexical structures, references, aliases, and graph relations.",
        "SQLite",
        public=False,
        encrypted=False,
        bidirectional=False,
        boundaries=["tb-rag-index-plane"],
    ),
    flow(
        "flow-provider-request",
        "provider request",
        "process-orchestrator-api",
        "actor-llm-provider",
        "Prompt, retrieved context, model parameters, provider credentials/references, and provider response cross the external provider trust boundary.",
        "HTTPS / provider API",
        public=True,
        encrypted=True,
        bidirectional=True,
        boundaries=["tb-tokenstream-runtime", "tb-external-providers-tools"],
        vertices=[{"x": 1120, "y": 136}],
    ),
    flow(
        "flow-mcp-tool-call",
        "MCP tool call",
        "process-orchestrator-api",
        "actor-mcp-server",
        "Tool discovery and execution against configured MCP servers/tools under policy allowlists.",
        "HTTP / streamable HTTP / local transport",
        public=True,
        encrypted=False,
        bidirectional=True,
        boundaries=["tb-tokenstream-runtime", "tb-external-providers-tools"],
        vertices=[{"x": 1120, "y": 330}],
    ),
]


model = {
    "version": "2.6.2",
    "summary": {
        "title": "TokenStream CRA STRIDE Data Flow and Trust Boundaries",
        "owner": "TBD: TokenStream maintainer / CRA readiness owner",
        "description": (
            "Diagram 2 Threat Dragon model for the TokenStream CRA risk assessment. "
            "This is the primary STRIDE DFD and trust-boundary diagram. Risk scoring is defined outside Threat Dragon."
        ),
        "id": "tokenstream-cra-stride-dfd-trust-boundaries-2026-08-26",
    },
    "detail": {
        "contributors": [{"name": "Codex"}],
        "reviewer": "TBD",
        "diagramTop": 1,
        "threatTop": 1,
        "diagrams": [
            {
                "id": 0,
                "title": "Diagram 2: STRIDE Data Flow + Trust Boundaries",
                "thumbnail": "./public/content/images/thumbnail.stride.jpg",
                "diagramType": "STRIDE",
                "version": "2.6.2",
                "description": (
                    "Primary STRIDE DFD for TokenStream. Flow names intentionally use the CRA risk assessment vocabulary: "
                    "chat request, management config write, runtime snapshot reload, provider request, MCP tool call, "
                    "source upload/fetch, and index write/query."
                ),
                "placeholder": "TokenStream CRA STRIDE DFD",
                "cells": cells,
            }
        ],
    },
}


OUT.write_text(json.dumps(model, indent=2) + "\n", encoding="utf-8")
print(OUT)
